# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

env = "development"

colorScheme = "blowfish"
defaultAppearance = "light"  # valid options: light or dark
autoSwitchAppearance = false

logo = "images/logo_light.png"
secondaryLogo = "images/logo_dark.png"

# defaultBackgroundImage = "/img/ocean.jpg"
# defaultFeaturedImage = "/img/ocean.jpg"

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

description = "Blog for all things programming related"
copyright = "Copyright © { year } devdot.blog"

disableImageZoom = true
disableImageOptimization = false
disableTextInHeader = true

showViews = false # only with Firebase integration
showLikes = false # only with Firebase integration

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "page" # valid options: page, profile, hero, card, background, custom
# homepageImage = "/img/iceland.jpg" # used in: hero, and card
showRecent = true
showRecentItems = 12
showMoreLink = true
showMoreLinkDest = "posts"
cardView = true
cardViewScreenWidth = false # true - wide layout, false - narrow layout
layoutBackgroundBlur = true # only used when layout equals background

[article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"    # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
sharingLinks = false       # or list of [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]
showCategory = true
showComments = true

[list]
showHero = false
heroStyle = "background"            # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true         # only used when heroStyle equals background
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"    # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = true
heroStyle = "background"    # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = false
groupByYear = true
cardView = true
cardViewScreenWidth = false

[firebase]
#  apiKey = "...."
#  authDomain = "...."
#  projectId = "...."
#  storageBucket = "...."
#  messagingSenderId = "...."
#  appId = "...."
#  measurementId = "...."

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[buymeacoffee]
#  identifier = "nunocoracao"
#  globalWidget = true
#  globalWidgetMessage = ""
#  globalWidgetColor = "#FFDD00"
#  globalWidgetPosition = "Right"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
