apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
  namespace: blog
spec:
  selector:
    matchLabels:
      name: blog-nginx
  template:
    metadata:
      labels:
        name: blog-nginx
    spec:
      containers:
        - name: blog-nginx
          image: ghcr.io/tokav/blog:latest
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            tcpSocket:
              port: http
