apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      labels:
        name: blog
    spec:
      containers:
        - name: blog
          image: ghcr.io/tkawczynski/blog:latest
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            tcpSocket:
              port: http
