apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      name: blog
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-docker-auth
      containers:
        - name: blog
