apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
spec:
  selector:
    matchLabels:
      name: blog-nginx
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-docker-auth
