[giscus]
enabled = true
repoName = "tokav/blog"
repoId = "R_kgDOK-2Lfw"             ## Use https://api.github.com/repos/USER/REPO to get repoID (JSON property 'node_id')
categoryName = "Blog"
categoryId = "DIC_kwDOK-2Lf84CpRvb"
mapping = "og:title"
theme = "light"
